### ISSUE TITLE
횡스크롤 without 스크롤

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/tip-archive#36]
```html
<ul>
  <li><a></a></li>
  <li><a></a></li>
  <li><a></a></li>
  <li><a></a></li>
  <li><a></a></li>
</ul>
```

```scss
ul {
  white-space: nowrap;
  overflow-x: scroll;
  -ms-overflow-style: none; // IE 10+
  overflow: -moz-scrollbars-none; // Firefox

  li {
    margin-right: 8px;
    display: inline-block;
    white-space: normal;

    a {
      display: block;
      padding: 14px 16px 16px 16px;
    }
  }
  li:last-child {
    margin-right: 0;
  }
}

ul::-webkit-scrollbar {
  display: none; // Safari and Chrome
}

```
