### ISSUE TITLE
Prevent double tap in web

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/tip-archive#44]
## Description

- Disable double tab 

### Solution 1

> Add meta tag with user-scalable

```html
<meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover,maximum-scale=1.0,user-scalable=0">
```

### Solution 2

> Add `touch-action` property to element

```css
/* Disable double tab in menu*/
.selector {
  touch-action: manipulation;
}
```
